import { ViewTransitions } from "next-view-transitions";
import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`antialiased bg-white min-h-dvh grid`}>
          <div className="bg-black text-white rounded-2xl relative m-0.5">
            <Navigation />
            <div style={{ viewTransitionName: "content" }}>{children}</div>
          </div>
        </body>
      </html>
    </ViewTransitions>
  );
}
